version: '3.8'

services:

  # back:
  #   image: shureck/panda_back:latest
  #   restart: always
    
  #   command: uvicorn main:app --reload --host 0.0.0.0

  #   # volumes:
  #   #     - ./zero_images/:/usr/src/zero_images/

  #   ports:
  #     - 8060:8000
  
  front:
    build: .    
    volumes:
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - "REACT_APP_API_URL=back:8000"
